title: "Sensoric"
tagline: "Pudełko pełne ekologicznych skarbów, co miesiąc z inną zawartością, dzięki którym Twoje dziecko ćwiczy integrację sensoryczną"
description: "Pudełko pełne ekologicznych skarbów, co miesiąc z inną zawartością, dzięki którym Twoje dziecko ćwiczy integrację sensoryczną. Gra przeznaczona dla dzieci w wieku 4 - 7 lat."
url: https://sensoric.eu
author: Sensoric
facebook:
  publisher: www.facebook.com/Sensoric.gra/
  admins: Sensoric.gra
logo: /assets/images/logo_hero.png
social:
  name: Sensoric
  links: 
    - https://www.facebook.com/Sensoric.gra/
    - https://www.instagram.com/sensoric.eu/
image: /assets/images/img_og.png
#height: "631"
#width: "1080"
#google_site_verification
locale: pl_PL

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier
  - jekyll-autoprefixer

jekyll-minifier:
  uglifier_args:
    harmony: true
  exclude: '*.php'

autoprefixer:
  browsers:
  - last 2 versions
  only_production: true

exclude:
  - build.sh

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/blog/:year/:month/:title/"

pagination:
  enabled: true
  debug: true
  collection: 'posts'
  per_page: 9
  permalink: '/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  locale: '' 
  trail: 
    before: 2
    after: 2
