title: "Sensoric - gra online do integracji sensorycznej"
tagline: "Sensoric to fabularna gra online do integracji sensorycznej dzieci w wieku 4 - 7 lat."
description: "Sensoric łączy zabawę z ćwiczeniami integracji sensorycznej wspomagając prawidłowy rozwój Twojego dziecka. Gra przeznaczona dla dzieci  w wieku 4 - 7 lat."
url: https://sensoric.eu
author: Sensoric
image: /assets/images/img_og.png
height: "631"
width: "1080"
facebook:
  publisher: https://www.facebook.com/Sensoric.gra/
  admins: Sensoric.gra
social:
  name: Sensoric
  links: 
    - https://www.facebook.com/Sensoric.gra/
    - https://www.instagram.com/sensoric.eu/
#google_site_verification
locale: pl_PL

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier
  - jekyll-autoprefixer

jekyll-minifier:
  uglifier_args:
    harmony: true

autoprefixer:
  browsers:
  - last 2 versions
  only_production: true

  
