title: Rozpocznij przygodę teraz!
subtitle: "Sensoric to:"
items:
  - text: zestaw fabularyzowanych ćwiczeń w formie animacji
  - text: 3 ćwiczenia dziennie, 12 dni w miesiącu
  - text: ok. 20 min zabawy każdego dnia
  - text: mix ćwiczeń kreatywnych, plastycznych i ruchowych
  - text: nowy miesiąc – nowe pudełko, nowe przygody
  - text: przybory z bezpiecznych, ekologicznych materiałów
price: 
  prefix: "cena:"
  value: 129
  sufix: zł/miesiąc 
button: Zamów